Repository alacritty/alacritty, pull requests merged in 2018-10, with the labels that each got.

#1374 Add support for Windows (Fixes #28)
  .gitignore
  .travis.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  INSTALL.md
  README.md
  alacritty_windows.yml
  appveyor.yml
  assets/windows/alacritty.ico
  assets/windows/alacritty.manifest
  assets/windows/windows.rc
  build.rs
  copypasta/Cargo.toml
  copypasta/src/lib.rs
  copypasta/src/windows.rs
  font/Cargo.toml
  font/src/darwin/mod.rs
  font/src/ft/mod.rs
  font/src/lib.rs
  font/src/rusttype/mod.rs
  src/config.rs
  src/display.rs
  src/event_loop.rs
  src/input.rs
  src/lib.rs
  src/main.rs
  src/renderer/mod.rs
  src/tty/mod.rs
  src/tty/unix.rs
  src/tty/windows.rs
  src/window.rs
  winpty/Cargo.lock
  winpty/Cargo.toml
  winpty/build.rs
  winpty/src/lib.rs
Labels: H - windows

#1699 Relax matching of URL modifiers
  src/config.rs
  src/input.rs
Labels: C - awaiting followup

#1709 Explicitly detach from the console on exit
  src/main.rs
Labels: C - awaiting feedback

#1686 Add cargo workspace, add winpty tests to CI
  .travis.yml
  Cargo.lock
  Cargo.toml
  appveyor.yml
  winpty/src/lib.rs
Labels: C - awaiting progress

#1721 Sync .app bundle timestamp during build
  Makefile
Labels: H - macos
