Repository alacritty/alacritty, pull requests merged in 2018-11, with the labels that each got.

#1600 Fix Selection While Scrolling
  CHANGELOG.md
  src/event.rs
Labels: C - awaiting progress

#1788 Fix i386 CI releases
  .travis.yml
  ci/before_deploy.sh
  ci/i386/Dockerfile
  ci/x86_64/Dockerfile
Labels: C - awaiting feedback

#1799 Add homebrew option for macOS installation.
  README.md
Labels: H - macos

#1715 Fix for an underflow on some type conversions
  CHANGELOG.md
  src/term/mod.rs
  src/tty/windows.rs
  winpty/src/windows.rs
Labels: C - awaiting feedback, H - windows
