Repository alacritty/alacritty, pull requests merged in 2019-08, with the labels that each got.

#2697 Move modifier check before URL search
  alacritty_terminal/src/grid/mod.rs
  alacritty_terminal/src/input.rs
  alacritty_terminal/src/term/mod.rs
  alacritty_terminal/src/url.rs
Labels: B - regression

#2664 Ignore unsupported CSI sequences
  CHANGELOG.md
  alacritty_terminal/src/ansi.rs
  alacritty_terminal/tests/ref.rs
  alacritty_terminal/tests/ref/selective_erasure/alacritty.recording
  alacritty_terminal/tests/ref/selective_erasure/config.json
  alacritty_terminal/tests/ref/selective_erasure/grid.json
  alacritty_terminal/tests/ref/selective_erasure/size.json
Labels: P - high

#2661 Always show Text mouse cursor when using Shift to select a block of text
  CHANGELOG.md
  alacritty_terminal/src/ansi.rs
  alacritty_terminal/src/event.rs
  alacritty_terminal/src/input.rs
  alacritty_terminal/src/term/mod.rs
Labels: C - awaiting progress
